name: Unit Tests

on:
    pull_request:
        branches:
            - main
    push:
        branches:
            - main

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x]

        env:
            PORT: ${{ secrets.PORT }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            MONGODB_URI: ${{ secrets.MONGODB_URI }}
            MAILER_USER: ${{ secrets.MAILER_USER }}
            MAILER_PORT: ${{ secrets.MAILER_PORT }}
            MAILER_SECURE: ${{ secrets.MAILER_SECURE }}
            MAILER_PASSWORD: ${{ secrets.MAILER_PASSWORD }}
            MAILER_HOST: ${{ secrets.MAILER_HOST }}
            ML_URL: ${{secrets.ML_URL}}
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: npm install
              run: npm ci

            - name: npm build
              run: npm run build

            - name: npm test
              run: npm test
